#!/bin/bash
echo "Pushing code to Gitlab..."
git push gitlab developer
git push gitlab  main

echo "changing git branch to developer..."
git checkout developer

echo "pushing code to Github..."

git push origin developer