services:
  - type: web
    name: smart-agri-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    buildCommand: cd backend && docker build -t smart-agri .
    #env: docker
   # port: 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartagri-db
          property: connectionString