"""update on livestock added more columns

Revision ID: 01b74227e0ba
Revises: 0db673ff154d
Create Date: 2026-04-17 21:19:07.765629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b74227e0ba'
down_revision: Union[str, Sequence[str], None] = '0db673ff154d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestock', sa.Column('status', sa.String(), nullable=True))
    op.add_column('livestock', sa.Column('archive_reason', sa.String(), nullable=True))
    op.add_column('livestock', sa.Column('archive_notes', sa.String(), nullable=True))
    op.add_column('livestock', sa.Column('archived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livestock', 'archived_at')
    op.drop_column('livestock', 'archive_notes')
    op.drop_column('livestock', 'archive_reason')
    op.drop_column('livestock', 'status')
    # ### end Alembic commands ###
