"""table upate for notification and nutrition

Revision ID: 0db673ff154d
Revises: 6bf074e7b082
Create Date: 2026-04-11 23:49:29.045406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0db673ff154d"
down_revision: Union[str, Sequence[str], None] = "6bf074e7b082"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("notification_type", sa.String(), nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("sms_enabled", sa.Boolean(), nullable=False),
        sa.Column("push_enabled", sa.Boolean(), nullable=False),
        sa.Column("whatsapp_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "notification_type"),
    )
    op.create_index(
        op.f("ix_notification_preferences_notification_type"),
        "notification_preferences",
        ["notification_type"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("notification_type", sa.String(), nullable=False),
        sa.Column("channels", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_status"), "notifications", ["status"], unique=False
    )
    op.create_table(
        "feed_purchases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=True),
        sa.Column("purchased_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feeds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feed_usage",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("quantity_used", sa.Float(), nullable=True),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.Column("livestock_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feeds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_deliveries_created_at"),
        "notification_deliveries",
        ["created_at"],
        unique=False,
    )
    op.alter_column(
        "livestock", "tag", existing_type=sa.VARCHAR(length=150), nullable=True
    )
    # Add if_exists=True to these three lines
    op.drop_index(
        op.f("idx_refresh_token_lookup"), table_name="refresh_token", if_exists=True
    )
    op.drop_index(
        op.f("idx_refresh_token_token"), table_name="refresh_token", if_exists=True
    )
    op.drop_index(op.f("idx_users_email"), table_name="users", if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.create_index(
        op.f("idx_refresh_token_token"), "refresh_token", ["token"], unique=False
    )
    op.create_index(
        op.f("idx_refresh_token_lookup"), "refresh_token", ["token"], unique=False
    )
    op.alter_column(
        "livestock", "tag", existing_type=sa.VARCHAR(length=150), nullable=False
    )
    op.drop_index(
        op.f("ix_notification_deliveries_created_at"),
        table_name="notification_deliveries",
    )
    op.drop_table("notification_deliveries")
    op.drop_table("feed_usage")
    op.drop_table("feed_purchases")
    op.drop_index(op.f("ix_notifications_status"), table_name="notifications")
    op.drop_index(
        op.f("ix_notifications_notification_type"), table_name="notifications"
    )
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        op.f("ix_notification_preferences_notification_type"),
        table_name="notification_preferences",
    )
    op.drop_table("notification_preferences")
    # ### end Alembic commands ###
