"""expected delivery column

Revision ID: 497cbe85195c
Revises: c0e189c8f823
Create Date: 2026-08-03 10:38:31.841238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497cbe85195c'
down_revision: Union[str, Sequence[str], None] = 'c0e189c8f823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestock', sa.Column('expectedDelivery', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payment', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_payment_idempotency_key'), 'payment', ['idempotency_key'], unique=True)
    op.execute("UPDATE users SET package_tier = 'BASIC' WHERE package_tier IS NULL")
    op.alter_column('users', 'package_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'package_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_payment_idempotency_key'), table_name='payment')
    op.drop_column('payment', 'idempotency_key')
    op.drop_column('livestock', 'expectedDelivery')
    # ### end Alembic commands ###
