"""updated users table

Revision ID: 4bacd3bc81ab
Revises: aad09c0a1d2d
Create Date: 2026-04-25 20:29:51.378150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bacd3bc81ab"
down_revision: Union[str, Sequence[str], None] = "aad09c0a1d2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_column("users", "is_active")
    # ### end Alembic commands ###
