"""tables livestock

Revision ID: b4f2bd02e94d
Revises: 245e23b50962
Create Date: 2026-03-24 20:08:19.598072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4f2bd02e94d"
down_revision: Union[str, Sequence[str], None] = "245e23b50962"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "livestock",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tag", sa.String(length=150), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("breed", sa.String(length=200), nullable=True),
        sa.Column("heatStatus", sa.Boolean(), nullable=True),
        sa.Column("pregnant", sa.Boolean(), nullable=True),
        sa.Column("lastInsemination", sa.DateTime(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("healthStatus", sa.String(length=200), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "createdAt", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("livestock")
    # ### end Alembic commands ###
