"""payment table and financial wallet

Revision ID: b9826ca97d09
Revises: 63f861eaabba
Create Date: 2026-04-20 21:06:02.105674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9826ca97d09'
down_revision: Union[str, Sequence[str], None] = '63f861eaabba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('checkout_request_id', sa.String(), nullable=True),
    sa.Column('merchant_request_id', sa.String(), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('result_code', sa.Integer(), nullable=True),
    sa.Column('result_desc', sa.String(length=255), nullable=True),
    sa.Column('raw_callback_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('account_reference', sa.String(length=100), nullable=True),
    sa.Column('transaction_desc', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checkout_status', 'payment', ['checkout_request_id', 'status'], unique=False)
    op.create_index('idx_user_status', 'payment', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_payment_checkout_request_id'), 'payment', ['checkout_request_id'], unique=True)
    op.create_index(op.f('ix_payment_mpesa_receipt_number'), 'payment', ['mpesa_receipt_number'], unique=True)
    op.create_index(op.f('ix_payment_status'), 'payment', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='PROTECT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_reference'), 'transactions', ['reference'], unique=True)
    op.alter_column('livestock', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_livestock_archived_at'), 'livestock', ['archived_at'], unique=False)
    op.create_index(op.f('ix_livestock_status'), 'livestock', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_livestock_status'), table_name='livestock')
    op.drop_index(op.f('ix_livestock_archived_at'), table_name='livestock')
    op.alter_column('livestock', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_transactions_reference'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payment_status'), table_name='payment')
    op.drop_index(op.f('ix_payment_mpesa_receipt_number'), table_name='payment')
    op.drop_index(op.f('ix_payment_checkout_request_id'), table_name='payment')
    op.drop_index('idx_user_status', table_name='payment')
    op.drop_index('idx_checkout_status', table_name='payment')
    op.drop_table('payment')
    # ### end Alembic commands ###
