"""table update for users, payment and livestock columns

Revision ID: c0e189c8f823
Revises: 4bacd3bc81ab
Create Date: 2026-05-20 23:14:09.144816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0e189c8f823'
down_revision: Union[str, Sequence[str], None] = '4bacd3bc81ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milk_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gross_revenue', sa.Float(), nullable=False),
    sa.Column('feed_costs', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('total_liters', sa.Float(), nullable=False),
    sa.Column('avg_price_per_liter', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milk_ledger_date'), 'milk_ledger', ['date'], unique=False)
    op.create_index(op.f('ix_milk_ledger_id'), 'milk_ledger', ['id'], unique=False)
    op.alter_column('feed_usage', 'quantity_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_foreign_key(None, 'feed_usage', 'livestock', ['livestock_id'], ['id'], ondelete='SET NULL')
    op.add_column('livestock', sa.Column('nextHeatDate', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('package_is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('package_tier', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('package_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'package_expiry')
    op.drop_column('users', 'package_tier')
    op.drop_column('users', 'package_is_active')
    op.drop_column('livestock', 'nextHeatDate')
    op.drop_constraint(None, 'feed_usage', type_='foreignkey')
    op.alter_column('feed_usage', 'quantity_used',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_milk_ledger_id'), table_name='milk_ledger')
    op.drop_index(op.f('ix_milk_ledger_date'), table_name='milk_ledger')
    op.drop_table('milk_ledger')
    # ### end Alembic commands ###
