"""livestock table new columns

Revision ID: f52b2554614c
Revises: b4f2bd02e94d
Create Date: 2026-03-26 23:06:08.633598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52b2554614c'
down_revision: Union[str, Sequence[str], None] = 'b4f2bd02e94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livestock', sa.Column('inseminationType', sa.String(length=100), nullable=True))
    op.add_column('livestock', sa.Column('birthDate', sa.DateTime(), nullable=True))
    op.add_column('livestock', sa.Column('motherTag', sa.String(length=150), nullable=True))
    op.add_column('livestock', sa.Column('fatherTag', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livestock', 'fatherTag')
    op.drop_column('livestock', 'motherTag')
    op.drop_column('livestock', 'birthDate')
    op.drop_column('livestock', 'inseminationType')
    # ### end Alembic commands ###
