name: Backend CI

on:
    push:
        branches: [ main ] 
        paths: [ 'backend/**' ] 
    pull_request:
        paths: [ 'backend/**' ]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install dependencies
              working-directory: ./backend
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest httpx pytest-asyncio
            - name: Run tests
              run: pytest --maxfail=1 --disable-warnings -v
    