name: Deployment and production

on: 
    workflow_run:
        workflows: ["Backend CI", "Frontend CI"]
        branches: [ main ]
        types: 
            - completed
jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v4

            - name: Deploy to render 
              run: | 
                echo "deploying to render ..."
                curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

            - name: Deploy Frontend
              env:
                VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              run: |
                echo "Deploying frontend to Vercel..."
                npx vercel --token "$VERCEL_TOKEN" --prod