name: Deployment and production

on: 
    workflow_run:
        workflows: ["Backend CI", "Frontend CI"]
        branches: [ main ]
        types: 
            - completed
jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest
        # steps:
            # - name: SSH and deploy
            #   uses: appleboy/ssh-action@v1
            #   with:
            #     host: ${{ secrets.SERVER_IP }}
            #     username: ${{ secrets.SERVER_USER }}
            #     key: ${{ secrets.SSH_PRIVATE_KEY }}
            #     script: |
            #        docker-compose pull
            #        docker-compose up -d