name: Deployment and production

on: 
    work_run:
        workflows: ["Backend CI", "Frontend CI"]
        branches: [ main ]
        types: 
            - completed
jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest
        steps:
            - name: SSH and deploy
              uses: appleboy/ssh-action@v1
              with:
                host: 
                username: 
                key:
                script: |
                   docker-compose pull
                   docker-compose up -d