name: Frontend CI

on:
    push:
        branches: [ 'frontend/**' ]
        pull_request:
            paths: [ 'frontend/**' ]
    
jobs:
    test:
        runs-on: Ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            
            - name: Install depencies
              run:  | 
              cd frontend
              npm install
            - name: Run tests
              run: | 
              cd frontend
              npm test
            
            build-docker:
                needs: test
                runs-on: ubuntu-latest
                steps:
                    - uses: actions/checkout@v4

                    - name: Log in to DOcker Hub
                      uses: docker/login-action@v2
                      with:
                        username:
                        password:
                    
                    - name: Build and push
                      uses: docker/build-push-action@v4
                      with: 
                        context: ./frontend
                        push: true
                        tags: myusername/frontend-app:latest