name: Frontend CI

on:
    push:
        branches: [ main ]
        paths: [ 'frontend/**']
    pull_request:
          paths: [ 'frontend/**' ]
    
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v3
              with: 
                node-version: 18
            
            - name: Install depencies
              working-directory: ./frontend
              run:  | 
                cd frontend
                npm install
            - name: Run tests
              run: | 
                cd frontend
                npm test
            - name: Build and deploy
              run: |
                cd backend
                next build
                npm run build
                
    
